version: '3.7'

services:
  wg-tunnel:
    image: whyvra/tunnel
    container_name: wg-tunnel
    hostname: wg-tunnel
    restart: always
    volumes:
      - ./data:/data:rw
      - ./data/appsettings.json:/srv/www/appsettings.json
# If Traefik comment ports
    ports:
      - "5800:5800"
# Traefik
    # networks:
      # - proxy
    # labels:
      # - "traefik.enable=true"
      # - "traefik.http.routers.wg-tunnel.entrypoints=web"
      # - "traefik.http.routers.wg-tunnel.rule=Host(`youdomain.com`)"
      # - "traefik.http.middlewares.wg-tunnel-https-redirect.redirectscheme.scheme=websecure"
      # - "traefik.http.routers.wg-tunnel.middlewares=wg-tunnel-https-redirect"
      # - "traefik.http.routers.wg-tunnel-secure.entrypoints=websecure"
      # - "traefik.http.routers.wg-tunnel-secure.rule=Host(`youdomain.com`)"
      # - "traefik.http.routers.wg-tunnel-secure.tls=true"
      # - "traefik.http.routers.wg-tunnel-secure.tls.certresolver=cloudflare"
      # - "traefik.http.routers.wg-tunnel-secure.service=wg-tunnel"
      # - "traefik.http.services.wg-tunnel.loadbalancer.server.port=5800"
      # - "traefik.docker.network=proxy"

# Traefik
# networks:
  # proxy:
    # external: true